import { Candidate, RecruiterMetrics } from '../types/recruiter';

export const mockCandidates: Candidate[] = [
    {
        id: '1',
        name: 'Sarah Chen',
        email: 'sarah.chen@email.com',
        avatar: 'https://i.pravatar.cc/150?img=1',
        fitScore: 92,
        skills: ['React', 'TypeScript', 'Node.js', 'AWS'],
        coverExcerpt: 'Passionate full-stack developer with 5 years of experience building scalable web applications...',
        status: 'new',
        source: 'QualityMatch',
        appliedAt: '2026-01-24T10:30:00Z',
        opportunityId: 101,
        opportunityTitle: 'Senior Full Stack Engineer',
        atsSynced: true,
    },
    {
        id: '2',
        name: 'Marcus Johnson',
        email: 'marcus.j@email.com',
        avatar: 'https://i.pravatar.cc/150?img=12',
        fitScore: 88,
        skills: ['Python', 'Django', 'PostgreSQL', 'Docker'],
        coverExcerpt: 'Backend specialist focused on API design and database optimization. Led migration of legacy systems...',
        status: 'new',
        source: 'LinkedIn',
        appliedAt: '2026-01-24T09:15:00Z',
        opportunityId: 102,
        opportunityTitle: 'Backend Engineer',
        atsSynced: false,
    },
    {
        id: '3',
        name: 'Emily Rodriguez',
        email: 'emily.r@email.com',
        avatar: 'https://i.pravatar.cc/150?img=5',
        fitScore: 95,
        skills: ['React Native', 'Swift', 'Kotlin', 'Firebase'],
        coverExcerpt: 'Mobile development expert with apps reaching 1M+ downloads. Strong in cross-platform solutions...',
        status: 'reviewed',
        source: 'QualityMatch',
        appliedAt: '2026-01-23T14:20:00Z',
        opportunityId: 103,
        opportunityTitle: 'Mobile Engineer',
        atsSynced: true,
    },
    {
        id: '4',
        name: 'David Kim',
        email: 'david.kim@email.com',
        avatar: 'https://i.pravatar.cc/150?img=14',
        fitScore: 78,
        skills: ['Java', 'Spring Boot', 'Microservices', 'Kubernetes'],
        coverExcerpt: 'Enterprise software engineer with focus on scalable microservices architecture...',
        status: 'reviewed',
        source: 'Direct',
        appliedAt: '2026-01-23T11:45:00Z',
        opportunityId: 101,
        opportunityTitle: 'Senior Full Stack Engineer',
        atsSynced: false,
    },
    {
        id: '5',
        name: 'Priya Patel',
        email: 'priya.p@email.com',
        avatar: 'https://i.pravatar.cc/150?img=9',
        fitScore: 91,
        skills: ['Vue.js', 'Nuxt', 'GraphQL', 'Tailwind'],
        coverExcerpt: 'Frontend engineer specializing in modern UI/UX and performance optimization...',
        status: 'interview',
        source: 'QualityMatch',
        appliedAt: '2026-01-22T16:00:00Z',
        opportunityId: 104,
        opportunityTitle: 'Frontend Engineer',
        atsSynced: true,
    },
    {
        id: '6',
        name: 'Alex Thompson',
        email: 'alex.t@email.com',
        avatar: 'https://i.pravatar.cc/150?img=13',
        fitScore: 85,
        skills: ['DevOps', 'Terraform', 'CI/CD', 'Monitoring'],
        coverExcerpt: 'DevOps engineer with deep expertise in cloud infrastructure and automation...',
        status: 'interview',
        source: 'Referral',
        appliedAt: '2026-01-22T13:30:00Z',
        opportunityId: 105,
        opportunityTitle: 'DevOps Engineer',
        atsSynced: false,
    },
    {
        id: '7',
        name: 'Jessica Lee',
        email: 'jessica.lee@email.com',
        avatar: 'https://i.pravatar.cc/150?img=10',
        fitScore: 89,
        skills: ['UI/UX Design', 'Figma', 'React', 'Design Systems'],
        coverExcerpt: 'Product designer who codes. Created design systems used by teams of 50+ developers...',
        status: 'offer',
        source: 'QualityMatch',
        appliedAt: '2026-01-21T10:00:00Z',
        opportunityId: 106,
        opportunityTitle: 'Product Designer',
        atsSynced: true,
    },
    {
        id: '8',
        name: 'Mohamed Hassan',
        email: 'mohamed.h@email.com',
        avatar: 'https://i.pravatar.cc/150?img=11',
        fitScore: 72,
        skills: ['C++', 'Computer Vision', 'OpenCV', 'TensorFlow'],
        coverExcerpt: 'Computer vision engineer with research background in ML and image processing...',
        status: 'rejected',
        source: 'LinkedIn',
        appliedAt: '2026-01-20T15:45:00Z',
        opportunityId: 107,
        opportunityTitle: 'ML Engineer',
        atsSynced: false,
    },
    {
        id: '9',
        name: 'Olivia Brown',
        email: 'olivia.b@email.com',
        avatar: 'https://i.pravatar.cc/150?img=16',
        fitScore: 94,
        skills: ['Data Science', 'Python', 'SQL', 'Tableau'],
        coverExcerpt: 'Data scientist with strong business acumen. Built predictive models that increased revenue by 25%...',
        status: 'interview',
        source: 'QualityMatch',
        appliedAt: '2026-01-24T08:00:00Z',
        opportunityId: 108,
        opportunityTitle: 'Data Scientist',
        atsSynced: true,
    },
    {
        id: '10',
        name: 'James Wilson',
        email: 'james.w@email.com',
        avatar: 'https://i.pravatar.cc/150?img=15',
        fitScore: 81,
        skills: ['Go', 'gRPC', 'Distributed Systems', 'Redis'],
        coverExcerpt: 'Backend engineer focused on high-performance distributed systems and real-time processing...',
        status: 'new',
        source: 'Direct',
        appliedAt: '2026-01-24T12:00:00Z',
        opportunityId: 101,
        opportunityTitle: 'Senior Full Stack Engineer',
        atsSynced: false,
    },
];

export const mockMetrics: RecruiterMetrics = {
    newApplications: mockCandidates.filter(c => c.status === 'new').length,
    averageFitScore: Math.round(mockCandidates.reduce((sum, c) => sum + c.fitScore, 0) / mockCandidates.length),
    conversionRate: 20, // Mock percentage
    totalCandidates: mockCandidates.length,
};
