#!/bin/bash

# Recruiter Dashboard - Quick Test Script
# Run this to test the dashboard features

echo "🚀 Recruiter Dashboard Test Script"
echo "=================================="
echo ""

# Check if dev server is running
if lsof -Pi :5173 -sTCP:LISTEN -t >/dev/null ; then
    echo "✅ Dev server is running on http://localhost:5173"
else
    echo "❌ Dev server is NOT running"
    echo "   Run: npm run dev (in tender-frontend directory)"
    exit 1
fi

echo ""
echo "📋 Manual Test Checklist:"
echo ""
echo "1. Navigate to: http://localhost:5173/recruiter"
echo "   (You must be logged in)"
echo ""
echo "2. Verify Metrics Cards:"
echo "   ✓ New Applications: 3"
echo "   ✓ Average Fit: 86%"
echo "   ✓ Conversion Rate: 20%"
echo "   ✓ Total Candidates: 10"
echo ""
echo "3. Test Filters:"
echo "   ✓ Search: Type 'Sarah' → Should show 1 result"
echo "   ✓ Search: Type 'React' → Should show candidates with React skill"
echo "   ✓ Fit Score: Select '90% and above' → Should show 3 candidates"
echo "   ✓ Source: Select 'QualityMatch' → Should show 5 candidates"
echo "   ✓ Clear all filters → Should show all 10 candidates"
echo ""
echo "4. Test Pipeline Columns:"
echo "   ✓ New: 3 candidates (blue header)"
echo "   ✓ Reviewed: 2 candidates (purple header)"
echo "   ✓ Interview: 3 candidates (amber header)"
echo "   ✓ Offer: 1 candidate (green header)"
echo "   ✓ Rejected: 1 candidate (gray header)"
echo ""
echo "5. Test Candidate Card Actions:"
echo "   ✓ Click 'Approve' on a 'New' candidate"
echo "      → Should move to 'Reviewed' column"
echo "   ✓ Click 'Approve' on a 'Reviewed' candidate"
echo "      → Should move to 'Interview' column"
echo "   ✓ Click 'Reject' on any candidate"
echo "      → Should move to 'Rejected' column"
echo "   ✓ Click 'Message' on any candidate"
echo "      → Should open email client (mailto:)"
echo ""
echo "6. Test Responsiveness:"
echo "   ✓ Desktop (1920px): All columns side-by-side"
echo "   ✓ Tablet (768px): Horizontal scroll"
echo "   ✓ Mobile (375px): Stacked view with scroll"
echo ""
echo "7. Verify Visual Polish:"
echo "   ✓ Fit score badges color-coded (green ≥85%, blue ≥70%, gray <70%)"
echo "   ✓ ATS sync badge shows for synced candidates"
echo "   ✓ Relative time labels (e.g., '2h ago', 'Yesterday')"
echo "   ✓ Skills tags truncated at 4 with '+N more'"
echo "   ✓ Hover states on cards and buttons"
echo ""
echo "=================================="
echo ""
echo "🧪 To run unit tests:"
echo "   cd tender-frontend"
echo "   npm run test"
echo ""
echo "✅ All tests passing = Feature is ready!"
echo ""
